### PR TITLE
Fix edit person to only allow editing name, email, and phone number

### LINKED ISSUE #233: [PE-D][Tester B] Feature Flaw: Editing person's project may completely replace all his previous projects and tasks
**Context:**
A person may have multiple projects and multiple tasks. Although this person is busy, they may be assigned even more tasks using the edit command.

**Expected:**
Thus, it is expected that the edit command allows adding of tasks and adding of projects to the person without removing the previously assigned tasks

**Actual:**
However, when the user wants to add new projects and/or tasks, the application may overwrite all the tasks and projects the user had with only the newly entered project and task.

**Steps to reproduce:** 
1. Start with the original jar file.
2. Run the following command:
`edit 1 -n Previously Alex -e weirdemail@weirddomain.com -p28348917239841723984918234 -l Interior -d add new feature -l manufacture -d read notes -d research on project -d task1`
3. This should (correctly) produce the following update to the first contact:

Image

This assigns 4 different tasks to the first person.

4. Then run the following command:
`edit 1 -n Previously Alex -e weirdemail@weirddomain.com -p28348917239841723984918234 -l Infrastructure`

It should produce the following output:

Image

5. This completely erases the previous tasks, even though the person may still have those tasks in progress.

Since this is a feature less useful than it could be, it is a FeatureFlaw.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### LINKED ISSUE #240: [PE-D][Tester B] Functionality Bug: Editing a person's project and tasks can sometimes fail although the input is valid
**Context:**
In some cases, a person already has a certain project but needs to be assigned more tasks from that project

**Expected:**
The application should receive this command and update the person's project with the specified task

**Actual:**
However, it seems the application treats it as if the person already has the task although they don't have that task yet.

**Steps to reproduce:** 
1. Start with the original jar release
2. Run the following command:

`find -n David`
`edit 1 -l Future Gen`

This will put David at the top of the person list panel
3. Run the following command:
`edit  1 -l Future Gen -d read notes -l Manufacture -d read notes`

4. The following should be displayed:

Image

The error message is wrong, saying that "This task already exists for this person!" although the task hasn't existed for that person 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #261: [PE-D][Tester B] Functionality Bug: On rare occasions, the application simply does not load anything when started
**Context:**
The application is used by entering a series of commands and has persistent storage. 

**Expected:**
Thus, users would expect data to be able to appear on the app. Otherwise, the data would just remain as JSON.

**Actual:**
Sometimes, the application displays an empty GUI as follows:

Image

Although the JSON file is not empty, the application still does not display anything:
 
**Steps to reproduce:** 
1. Start with the original jar release file
2. Run the following commands in order:
`edit 1 -l Manufacture -d read notes`
`edit 1 -l Mobile App`
3. Close the programme by closing the window using the red X on Mac.
4. Open the programme again by using `java -jar taskforge.json`
5. The following will be displayed:

Image

-------------
Labels: `severity.High` `type.FunctionalityBug`

### LINKED ISSUE #290: Edit person allows duplicate email and phone without complaining

### PR DESCRIPTION
**Pull request by ZealousGinger**
Also fixes editing duplicate email and phone bug so the pr is longer.

Closes #240
Closes #233 
Closes #261 
Closes #290

### CODE REVIEW

File: src/main/java/seedu/taskforge/logic/commands/person/EditCommand.java [hunk 1]
```diff
@@ -86,9 +71,9 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         Person personToEdit = lastShownList.get(index.getZeroBased());
-        Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor, model);
+        Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
 
-        if (!personToEdit.isSamePerson(editedPerson) && model.hasPerson(editedPerson)) {
+        if (hasConflictingIdentity(model, personToEdit, editedPerson)) {
```
Comment (HoangVu123456) [inline src/main/java/seedu/taskforge/logic/commands/person/EditCommand.java:76]: I don't understand this part, why need to change to this?

File: src/main/java/seedu/taskforge/model/person/UniquePersonList.java [hunk 2]
```diff
@@ -61,7 +61,10 @@ public void setPerson(Person target, Person editedPerson) {
             throw new PersonNotFoundException();
         }
 
-        if (!target.isSamePerson(editedPerson) && contains(editedPerson)) {
+        boolean hasConflict = internalList.stream()
+                .filter(person -> !person.equals(target))
+                .anyMatch(editedPerson::isSamePerson);
+        if (hasConflict) {
```
Comment (HoangVu123456) [inline src/main/java/seedu/taskforge/model/person/UniquePersonList.java:67]: Is this part need to change?

**Review by HoangVu123456 — COMMENTED** [review]
LGTM, just that there are some parts Im not quite sure how you change the comparison logic

File: src/main/java/seedu/taskforge/logic/commands/person/EditCommand.java (hunk 1 above)
Comment (ZealousGinger) [reply src/main/java/seedu/taskforge/logic/commands/person/EditCommand.java:76]: `model.hasPerson` is checking the persons whether it contains the editedPerson. It does not check whether the person is Unique i.e. unique email & phone number

File: src/main/java/seedu/taskforge/model/person/UniquePersonList.java (hunk 2 above)
Comment (ZealousGinger) [reply src/main/java/seedu/taskforge/model/person/UniquePersonList.java:67]: yes because the model does not check if there is duplicate person email and phone, so I have to add this check manually.

**Review by jiaqixu1 — COMMENTED** [review]
LGTM
